In [ ]:
import numpy as np
import torch
import random 
tt = np.zeros_like(np.arange(190).reshape(1, 190) , bool)
for i in range(190):
    if random.random() > 0.5:
        tt[0][i] = True
    else:
        tt[0][i] = False
tt = torch.tensor(tt )

print(tt.shape,tt)


tt = np.zeros_like(np.arange(190).reshape(1, 190,1) , float)
for i in range(190):
    tt[0][i] =  random.random()
tt = torch.tensor(tt )

print(tt.shape,tt)



In [2]:
idx = 10
n_pcs = torch.tensor(np.array([[1286, 314,   30,   30 , 366,  301 , 877,  624,  129,  403,  428,  212,    0,    0,  0 ,   0,    0,    0,    0,    0]]))
print(n_pcs.shape)
n_pcs_cumsum = n_pcs.cumsum(dim=1)
print(n_pcs_cumsum)
pc_st1 = 0 if idx == 0 else n_pcs_cumsum[0, idx - 1]
print(pc_st1)
pc_ed1 = n_pcs_cumsum[0, idx]
print(pc_ed1)

torch.Size([1, 20])
tensor([[1286, 1600, 1630, 1660, 2026, 2327, 3204, 3828, 3957, 4360, 4788, 5000,
         5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]])
tensor(4360)
tensor(4788)


In [3]:
data_id = 16

print("matching_data")
data = np.load(f'/disk2/data/breaking-bad-dataset/data/matching_data/{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,type(data[item]),data[item])
    except:
        print("ERROR",item)
        pass
    
print("\n","pc_data")
data = np.load(f'/disk2/data/breaking-bad-dataset/data/pc_data/everyday/val/000{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass


print("\n","verifier_data")
data = np.load(f'/disk2/data/breaking-bad-dataset/data/verifier_data/{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass


matching_data
edges (32, 2) <class 'numpy.ndarray'> [[ 1  0]
 [ 5  0]
 [ 6  0]
 [ 7  0]
 [ 9  0]
 [10  0]
 [ 4  1]
 [ 5  1]
 [11  1]
 [ 3  2]
 [ 7  2]
 [11  2]
 [ 8  3]
 [11  3]
 [ 6  5]
 [ 7  5]
 [ 9  5]
 [10  5]
 [11  5]
 [ 7  6]
 [ 8  6]
 [ 9  6]
 [10  6]
 [11  6]
 [ 8  7]
 [10  7]
 [11  7]
 [ 9  8]
 [10  8]
 [10  9]
 [11  9]
 [11 10]]
ERROR correspondence
gt_pcs (5000, 3) <class 'numpy.ndarray'> [[-0.12316637 -0.0748463  -0.21200943]
 [-0.07170958  0.129898    0.05592548]
 [ 0.11838685 -0.07271845  0.06463178]
 ...
 [-0.14312303  0.06455568 -0.4935415 ]
 [-0.09513497  0.02020543 -0.37322292]
 [ 0.00956341  0.00220429 -0.37117305]]
critical_pcs_idx (5000,) <class 'numpy.ndarray'> [0 4 7 ... 0 0 0]
n_pcs (20,) <class 'numpy.ndarray'> [1286  314   30   30  366  301  877  624  129  403  428  212    0    0
    0    0    0    0    0    0]
n_critical_pcs (20,) <class 'numpy.ndarray'> [489 188  30  30  88 285 544 495 129 238 360 196   0   0   0   0   0   0
   0   0]

 pc_data
data_id () 16

In [23]:
mat_mask = torch.triu(torch.ones(20, 20, dtype=torch.bool), diagonal=1)

In [27]:
mat_mask.sum()

tensor(190)

In [ ]:
logits torch.Size([1, 190, 1])